server:
  port: '9001'
spring:
  application:
    name: ADDRESS-SERVICE
  datasource:
    password: vinoth
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://postgresqldb:5432/postgres?createDatabaseIfNotExist=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect        
        format_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
      show-sql: 'true'