version: '3.1'
services:
  address-service:
    container_name: address-service
    image: address-service
    build: ./
    ports:
      - "9001:9001"
    depends_on:
      - postgresqldb
    volumes:
      - addressapp:/var/lib/postgresql/data
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=vinoth
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
volumes:
  addressapp:
